### ISSUE TITLE
unable to use cellranger with your fastq files

### ISSUE THREAD

**Issue by castro019** [cjh-lab/NCOMMS_NSCLC_scFibs#1]
Hello, 

I am unable to use cellranger count to align the fastq files that your paper provides. Might that be an issue with the barcodes that you use (not compatible with cellranger pipeline)? Or do you think one should be able to use cellranger count on the fastq files that you provide? 

Thanks for your time.

**Comment by cjh-lab** [comment]
Hello, these fastq files are from Drop-seq not 10X so cellranger will not work. See the McCarroll lab protocol here https://github.com/broadinstitute/Drop-seq/blob/master/doc/Drop-seq_Alignment_Cookbook.pdf
BW
________________________________
From: Sarah Castro ***@***.***>
Sent: Tuesday, March 19, 2024 20:17
To: cjh-lab/NCOMMS_NSCLC_scFibs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cjh-lab/NCOMMS_NSCLC_scFibs] unable to use cellranger with your fastq files (Issue #1)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
CAUTION: This e-mail originated outside the University of Southampton.

Hello,

I am unable to use cellranger count to align the fastq files that your paper provides. Might that be an issue with the barcodes that you use (not compatible with cellranger pipeline)? Or do you think one should be able to use cellranger count on the fastq files that you provide?

Thanks for your time.

**Comment by castro019** [comment]
@cjh-lab  Thank you. Another question (this may be because I am unfamilar with Drop-seq) but on the SRA website, it says, for example, that SRR12164463 has two spots per run (here is the link: https://trace.ncbi.nlm.nih.gov/Traces/index.html?view=run_browser&acc=SRR12164463&display=metadata) but when I fastq-dump and use --split-files, it only downloads one (SRR12164463_1.fastq), but there is not a second fastq/ read file for this SRR number (SRR12164463), which would be SRR12164463_2.fastq?   

There is another SRR number that correlates to the same donor as SRR12164463 (SRR12164464/ donor 7) but again, fastq-dump on this SRR only gives one file: SRR12164464_2.fastq.   Is this R1 and R2 for donor 7, even though each SRR says there 2 spots per run for each run? I would normally expect to get 4 files from these two SRR numbers, SRR12164463_1.fastq, SRR12164463_2.fastq, SRR12164464_1.fastq, and SRR12164464_2.fastq

I appreciate your help.
